name: Build
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.9"
      - name: Install Requirements
        run: |
          python -m pip install -U requests "setuptools>=80.9.0"
          python -m pip install "https://github.com/pyinstaller/pyinstaller/archive/develop.zip"

      - name: Build
        run: |
          pyinstaller --name=pyi-pkg-demo --noconfirm --onefile ./pyi_pkg_demo/__main__.py

      - name: Verify
        run: |
          ./dist/pyi-pkg-demo.exe
